### ISSUE TITLE
build.phonegap version conflict cordova-plugin-file@5.0.0

### ISSUE THREAD

**Issue by oleksiy-nesterov** [photokandyStudios/PKVideoThumbnail#17]
`
"plugman install --platform android --project /project --plugin cordova-plugin-photokandy-video-thumbnail": Fetching plugin "cordova-plugin-photokandy-video-thumbnail" via npm
Installing "cordova-plugin-photokandy-video-thumbnail" at "2.1.0" for android
Failed to install 'cordova-plugin-photokandy-video-thumbnail': CordovaError: Version of installed plugin: "cordova-plugin-file@5.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:581:33
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:509:49
    at flush (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Version of installed plugin: "cordova-plugin-file@5.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
`

**Comment by andreac** [comment]
same issue and if I start the app get this
`Property 'PKVideoThumbnail' does not exist on type 'Window'.`

**Comment by benmcmaster** [comment]
Hey @kerrishotts any insight on this? Would this be hard to upgrade?

**Comment by jdnichollsc** [comment]
@oleksiy-nesterov what platform?
