### ISSUE TITLE
Attempt to invoke virtual method boolean android.graphics.Bitmap.compress

### ISSUE THREAD

**Issue by kmturley** [photokandyStudios/PKVideoThumbnail#4]
Getting this error it seems like when it encounters a video with an unsupported codec:

    10-14 21:53:33.344  16813-16863/? E/PluginManager﹕ Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
    at com.photokandy.PKVideoThumbnail.PKVideoThumbnail.execute(PKVideoThumbnail.java:79)
    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:95)
    at org.apache.cordova.PluginManager.exec(PluginManager.java:130)
    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)

Might be worth having a line of code to check if thumbnail created was null, and return a message e.g.

    Bitmap thumbnail = ThumbnailUtils.createVideoThumbnail ( sourceVideo.substring(7), MediaStore.Images.Thumbnails.MINI_KIND);
    if (thumbnail == null) {
        callbackContext.error("issue with video codec or something else");
        return true;
    }

Thanks for the plugin!

**Comment by kerrishotts** [comment]
Should be fixed in 2.x
